### ISSUE TITLE
Simple CNN

### ISSUE THREAD

**Issue by w821881341** [bhanML/Co-teaching#6]

**Comment by w821881341** [comment]
I saw that The accuracy of simple CNN is about 60% according to your paper(Mnist pair 45% noisy).
But when I replace the model in this project with simple CNN, it can get about 85%.
Specifically, I just use one CNN in Co-teaching model and use its loss to update itself.

**Comment by LiJunnan1992** [comment]
I also have accuracy>80% using just one CNN. Would be great if the authors can give some reasons for this.

**Comment by jiaoyiping630** [comment]
I got same result with a single CNN.
I also found that, if I disable the intuition which use 100% samples to update and later use less proportion, I mean, if I always use 55% proportion to update under 55% noise rate, the training is similar to normal training. I thought the 100%->55% update schedule is the key rather than two-model-interact pipeline.

**Comment by w821881341** [comment]
@jiaoyiping630  You get it
